run:
  timeout: 2m

linters:
  disable-all: true
  enable:
    - dupl
    - errcheck
    - errname
    - errorlint
    - funlen
    - gci
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - makezero
    - misspell
    - nolintlint
    - prealloc
    - reassign
    - revive
    - staticcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - unused
    - usetesting

linters-settings:
  gocritic:
    disabled-checks:
      - exitAfterDefer
  thelper:
    test:
      begin: false

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - unparam
        - prealloc
        - funlen
