version: '3.5'

services:
  nats:
    container_name: nats-streaming
    image: nats-streaming:latest
    networks: ["nats-streaming"]
    ports:
      - "4222:4222"
      - "8222:8222"
    command: -store file -dir datastore

networks: 
  nats-streaming:
    name: nats-streaming
